server:
  port: 8080
spring:
  security:
    user:
      name: user
      password: a123456
logging:
  path: ./logs
  level:
    com.zaxxer.hikari.HikariConfig: info
    com.zaxxer.hikari.pool.HikariPool: info
    org.apache.curator.framework.recipes.cache.TreeCache: info
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: info
datasource:
  topzf:
    jdbc-url: jdbc:oracle:thin:@192.168.22.235:1521/auditdb
    username: topzf
    password: topzf
    minimum-idle: 5
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1 FROM DUAL
    pool-name: DatebookHikariCP
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mcap:
    jdbc-url: jdbc:oracle:thin:@192.168.22.235:1521/auditdb
    username: smkmcap
    password: smkmcap96225
    minimum-idle: 5
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1 FROM DUAL
    pool-name: DatebookHikariCP
    driver-class-name: oracle.jdbc.driver.OracleDriver

center:
  acc:
    url: http://192.168.23.152:1122/atom
    version: 1.0